import type { Sku } from './types';

/** Seeded demo catalog, 42 SKUs across a plausible grocery spread. */
const raw: [code: string, name: string, emoji: string, category: string][] = [
  ['0411', 'Bananas', '🍌', 'Produce'],
  ['0412', 'Organic Honeycrisp apples, 3 lb bag', '🍎', 'Produce'],
  ['0413', 'Hass avocados, 4 ct', '🥑', 'Produce'],
  ['0414', 'Baby spinach, 10 oz', '🥬', 'Produce'],
  ['0415', 'Roma tomatoes, per lb', '🍅', 'Produce'],
  ['0416', 'Yellow onions, 2 lb', '🧅', 'Produce'],
  ['0417', 'Seedless red grapes, per lb', '🍇', 'Produce'],
  ['0418', 'Lemons, 2 ct', '🍋', 'Produce'],
  ['0419', 'Navel oranges, 4 ct', '🍊', 'Produce'],
  ['0420', 'Pineapple', '🍍', 'Produce'],
  ['0421', 'Mini watermelon', '🍉', 'Produce'],
  ['0422', 'Strawberries, 1 lb', '🍓', 'Produce'],
  ['0423', 'Red bell pepper', '🫑', 'Produce'],
  ['0424', 'Sweet corn, 2 ct', '🌽', 'Produce'],
  ['0425', 'Garlic bulb', '🧄', 'Produce'],
  ['1121', 'Whole milk, 1 gal', '🥛', 'Dairy'],
  ['1122', 'Large eggs, dozen', '🥚', 'Dairy'],
  ['1123', 'Salted butter, 1 lb', '🧈', 'Dairy'],
  ['1124', 'Greek yogurt, vanilla, 32 oz', '🥣', 'Dairy'],
  ['1125', 'Sharp cheddar block, 8 oz', '🧀', 'Dairy'],
  ['1126', 'Oat milk, 64 oz', '🌾', 'Dairy'],
  ['2231', 'Sourdough loaf', '🍞', 'Bakery'],
  ['2232', 'Everything bagels, 6 ct', '🥯', 'Bakery'],
  ['2233', 'Croissants, 4 ct', '🥐', 'Bakery'],
  ['2234', 'Flour tortillas, 10 ct', '🫓', 'Bakery'],
  ['3341', 'Boneless chicken breast, per lb', '🍗', 'Meat'],
  ['3342', 'Ground beef 85/15, 1 lb', '🥩', 'Meat'],
  ['3343', 'Atlantic salmon fillet, per lb', '🐟', 'Meat'],
  ['3344', 'Uncured bacon, 12 oz', '🥓', 'Meat'],
  ['4451', 'Penne rigate, 16 oz', '🍝', 'Pantry'],
  ['4452', 'Marinara sauce, 24 oz', '🫙', 'Pantry'],
  ['4453', 'Long grain rice, 2 lb', '🍚', 'Pantry'],
  ['4454', 'Creamy peanut butter, 16 oz', '🥜', 'Pantry'],
  ['4455', 'Honey Nut Oat Cereal, family size', '🥣', 'Pantry'],
  ['4456', 'Extra virgin olive oil, 500 ml', '🫒', 'Pantry'],
  ['4457', 'Black beans, 15 oz can', '🥫', 'Pantry'],
  ['4458', 'Chicken stock, 32 oz', '🍲', 'Pantry'],
  ['5561', 'Tortilla chips, 13 oz', '🌮', 'Snacks'],
  ['5562', 'Dark chocolate bar, 3.5 oz', '🍫', 'Snacks'],
  ['5563', 'Trail mix, 26 oz', '🥨', 'Snacks'],
  ['5564', 'Sparkling water, 12 pk', '🫧', 'Beverages'],
  ['5565', 'Cold brew concentrate, 32 oz', '☕', 'Beverages'],
  ['5566', 'Orange juice, 52 oz', '🍊', 'Beverages'],
  ['6671', 'Paper towels, 6 rolls', '🧻', 'Household'],
  ['6672', 'Dish soap, 19 oz', '🧼', 'Household'],
  ['6673', 'Laundry detergent, 46 oz', '🧺', 'Household'],
  ['6674', 'Trash bags, 45 ct', '🗑️', 'Household'],
  ['7781', 'Dog treats, chicken, 16 oz', '🦴', 'Pet'],
  ['7782', 'Cat litter, 20 lb', '🐈', 'Pet'],
];

export const CATALOG: Sku[] = raw.map(([code, name, emoji, category]) => ({
  id: `sku_${code}`,
  code,
  name,
  emoji,
  category,
}));
